image: "registry.gitlab.cc-asp.fraunhofer.de:4567/simphony/documentation:latest"

before_script:
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cc-asp.fraunhofer.de/simphony/osp-core
  - cd osp-core
  - python3 setup.py install
  - cd ..

cache:
  # Required to keep artifacts from old builds
  paths:
    - public

test:
  stage: test
  script:
  - python setup.py build_sphinx
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
  - VERSION=$(python -c "import packageinfo; print(packageinfo.VERSION)")
  - python setup.py build_sphinx
  - cd public || { mkdir public && cd public; }
  - rm -r $VERSION || true
  - mkdir $VERSION
  - cp -r ../docs/build/html/* $VERSION
  - LATEST=$(ls -dr *.*.* | head -1)  # Reversed version folders without /
  - echo "$LATEST"
  # Check here if $VERSION == latest
  - >
    if [ "$VERSION" == "$LATEST" ]; then
      rm -rf latest/* || mkdir latest
      cp -r $VERSION/* latest
    fi
  # Write all versions in a file for the sidebar links
  - ls -rd */ | sed 's#/##' > available_versions.txt
  artifacts:
    name: "$VERSION"
    paths:
      - public
  only:
  - master

