image: "registry.gitlab.cc-asp.fraunhofer.de:4567/simphony/documentation:latest"

before_script:
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cc-asp.fraunhofer.de/simphony/osp-core
  - cd osp-core
  - python3 setup.py install

test:
  stage: test
  script:
  - sphinx-build -b html docs/source public
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
  - sphinx-build -b html docs/source public
  artifacts:
    paths:
    - public
  only:
  - master
