name: Test build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install pandoc
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: Build docs
      run: python setup.py install
